# Analyse de Transactions Immobilières avec Pandas

## Contexte
Vous travaillez pour une agence immobilière qui souhaite analyser les transactions de l'année passée. Vous disposez d'un jeu de données contenant les informations sur les ventes effectuées.

## Objectifs
L'objectif est d'utiliser la bibliothèque Pandas pour nettoyer les données et extraire des indicateurs statistiques clés.

---

## Questions de l'exercice

### 1. Préparation et Inspection
- Chargez le fichier (ou créez un DataFrame de test).
- Affichez les 10 premières lignes du jeu de données.
- Affichez le nombre de lignes et de colonnes.
- Identifiez les types de données pour chaque colonne.

---

In [1]:
import pandas as pd
import numpy as np

data = [
    [10138.0, "2024-07-02", "Appartement", "Fès", 758780.43, 56.4, 4.0, 12498.02],
    [10036.0, "2024-09-27", "Maison", "Kénitra", 3001220.85, 251.8, 7.0, 11360.84],
    [10169.0, "2024-03-29", "Riad", "Oujda", 2157663.07, 394.5, 5.0, 5691.59],
    [10143.0, "2024-08-03", "Studio", "Tanger", 359788.85, 35.5, 1.0, 10916.71],
    [10126.0, "2024-06-29", "Riad", "Tétouan", 4719708.5, 373.6, 6.0, 13203.18],
    [10133.0, "2024-10-14", "Studio", "Fès", 283368.91, 24.5, 1.0, 11349.0],
    [10102.0, "2024-05-27", "Maison", "Fès", 1604255.58, 244.1, 4.0, 6374.59],
    [10032.0, "2024-12-02", "Riad", "Tétouan", 1320735.93, 223.9, 8.0, 6321.58],
    [10120.0, "2024-10-16", "Studio", "Agadir", 289579.28, 30.2, 1.0, None],
    [10145.0, "2024-01-16", "Maison", "Safi", 1385490.38, 270.1, 7.0, 5014.54],
    [10022.0, "2024-06-18", "Maison", "Casablanca", 919095.58, 106.3, 3.0, 8119.55],
    [10115.0, "01/12/2024", "Appartement", "El Jadida", 341417.21, 56.5, 5.0, 6407.6],
    [10163.0, "2024-04-27", "Appartement", "El Jadida", 1006698.82, 130.9, 3.0, 7650.71],
    [10119.0, "2024-01-15", "Studio", "Safi", 286854.43, 42.1, 1.0, 7039.51],
    [10085.0, "2024-04-08", "Maison", "Fès", 1495111.14, 251.7, 5.0, 6207.69],
    [10111.0, "2024-09-04", "Appartement", "Tétouan", 1893357.75, 111.7, 5.0, 17096.6],
    [10109.0, "10/03/2024", "Appartement", "Kénitra", 1057404.28, 61.6, 3.0, 17143.05],
    [10161.0, "2024-01-24", "Maison", "Agadir", 2132198.13, 246.0, 7.0, None],
    [10051.0, "06/12/2024", "Studio", "Oujda", 326406.14, 38.5, 1.0, 9104.51],
    [10045.0, "2024-02-25", "Maison", "Oujda", 1564493.15, 288.7, 4.0, 5180.88],
    [10074.0, "14/01/2024", "Maison", "Safi", 2127335.12, 255.2, 4.0, 8893.62],
    [10066.0, "2024-06-29", "Maison", "Safi", 476504.61, 94.5, 7.0, 5475.23],
    [10122.0, "2024-05-27", "Maison", "Agadir", 2292755.23, 195.7, 3.0, 11781.16],
    [10096.0, "2024-11-27", "Appartement", "Agadir", 1714835.48, 135.6, 3.0, 12556.75],
    [10013.0, "2024-02-28", "Maison", "El Jadida", 1940340.74, 211.7, 7.0, 9942.67],
    [10166.0, "2024-07-04", "Riad", "Marrakech", 5094063.77, 390.4, 8.0, 12664.12],
    [10086.0, "28/10/2024", "Villa", "Youssoufia", 4155236.67, 545.1, 6.0, 7642.21],
    [10178.0, "09/05/2024", "Maison", "Fès", 828116.25, 105.2, 3.0, 8017.34],
    [10155.0, "2024-11-14", "Studio", "Tétouan", 455138.66, 27.2, 1.0, 15552.2],
    [10134.0, "2024-07-28", "Maison", "Oujda", 933920.85, 104.5, 6.0, 9229.14],
    [10128.0, "2024-07-31", "Studio", "Casablanca", 392307.07, 35.3, 1.0, 11490.19],
    [10024.0, "2024-08-04", "Studio", "Youssoufia", 171926.09, 31.4, 1.0, 5536.43],
    [10167.0, "07/06/2024", "Studio", "Tanger", 464555.93, 32.0, 1.0, 14763.59],
    [10125.0, "17/12/2024", "Villa", "Casablanca", 12500693.43, 689.0, 10.0, 19693.18],
    [10097.0, "18/10/2024", "Appartement", "Marrakech", 1082969.32, 53.2, 3.0, 20051.64]
]

columns = [
    "id_transaction",
    "date",
    "type_bien",
    "ville",
    "prix_vente",
    "surface_m2",
    "nombre_pieces",
    "prix_m2"
]

df = pd.DataFrame(data, columns=columns)

df.head()

,id_transaction,date,type_bien,ville,prix_vente,surface_m2,nombre_pieces,prix_m2
0,10138.0,2024-07-02,Appartement,Fès,758780.43,56.4,4.0,12498.02
1,10036.0,2024-09-27,Maison,Kénitra,3001220.85,251.8,7.0,11360.84
2,10169.0,2024-03-29,Riad,Oujda,2157663.07,394.5,5.0,5691.59
3,10143.0,2024-08-03,Studio,Tanger,359788.85,35.5,1.0,10916.71
4,10126.0,2024-06-29,Riad,Tétouan,4719708.50,373.6,6.0,13203.18


### 2. Nettoyage des données
- Vérifiez s'il y a des valeurs manquantes dans le DataFrame.
- Si la colonne `prix_m2` contient des valeurs nulles, remplacez-les par la moyenne de la colonne.
- Supprimez les lignes qui ne possèdent pas de "Numéro de transaction".

In [2]:


print(df[df.isna().any(axis=1)])

df["prix_vente"] = df["prix_vente"].fillna(df["prix_vente"].mean())

df = df[df['id_transaction'].notnull()]

df

    id_transaction        date type_bien   ville  prix_vente  surface_m2  \
8          10120.0  2024-10-16    Studio  Agadir   289579.28        30.2
17         10161.0  2024-01-24    Maison  Agadir  2132198.13       246.0

    nombre_pieces  prix_m2
8             1.0      NaN
17            7.0      NaN

,id_transaction,date,type_bien,ville,prix_vente,surface_m2,nombre_pieces,prix_m2
0,10138.0,2024-07-02,Appartement,Fès,758780.43,56.4,4.0,12498.02
1,10036.0,2024-09-27,Maison,Kénitra,3001220.85,251.8,7.0,11360.84
2,10169.0,2024-03-29,Riad,Oujda,2157663.07,394.5,5.0,5691.59
3,10143.0,2024-08-03,Studio,Tanger,359788.85,35.5,1.0,10916.71
4,10126.0,2024-06-29,Riad,Tétouan,4719708.50,373.6,6.0,13203.18
5,10133.0,2024-10-14,Studio,Fès,283368.91,24.5,1.0,11349.00
6,10102.0,2024-05-27,Maison,Fès,1604255.58,244.1,4.0,6374.59
7,10032.0,2024-12-02,Riad,Tétouan,1320735.93,223.9,8.0,6321.58
8,10120.0,2024-10-16,Studio,Agadir,289579.28,30.2,1.0,NaN
9,10145.0,2024-01-16,Maison,Safi,1385490.38,270.1,7.0,5014.54
10,10022.0,2024-06-18,Maison,Casablanca,919095.58,106.3,3.0,8119.55
11,10115.0,01/12/2024,Appartement,El Jadida,341417.21,56.5,5.0,6407.60
12,10163.0,2024-04-27,Appartement,El Jadida,1006698.82,130.9,3.0,7650.71
13,10119.0,2024-01-15,Studio,Safi,286854.43,42.1,1.0,7039.51
14,10085.0,2024-04-08,Maison,Fès,1495111.14,251.7,5.0,6207.69
15,10111.0,2024-09-04,Appartement,Tétouan,1893357.75,111.7,5.0,17096.60
16,10109.0,10/03/2024,Appartement,Kénitra,1057404.28,61.6,3.0,17143.05
17,10161.0,2024-01-24,Maison,Agadir,2132198.13,246.0,7.0,NaN
18,10051.0,06/12/2024,Studio,Oujda,326406.14,38.5,1.0,9104.51
19,10045.0,2024-02-25,Maison,Oujda,1564493.15,288.7,4.0,5180.88
20,10074.0,14/01/2024,Maison,Safi,2127335.12,255.2,4.0,8893.62
21,10066.0,2024-06-29,Maison,Safi,476504.61,94.5,7.0,5475.23
22,10122.0,2024-05-27,Maison,Agadir,2292755.23,195.7,3.0,11781.16
23,10096.0,2024-11-27,Appartement,Agadir,1714835.48,135.6,3.0,12556.75
24,10013.0,2024-02-28,Maison,El Jadida,1940340.74,211.7,7.0,9942.67
25,10166.0,2024-07-04,Riad,Marrakech,5094063.77,390.4,8.0,12664.12
26,10086.0,28/10/2024,Villa,Youssoufia,4155236.67,545.1,6.0,7642.21
27,10178.0,09/05/2024,Maison,Fès,828116.25,105.2,3.0,8017.34
28,10155.0,2024-11-14,Studio,Tétouan,455138.66,27.2,1.0,15552.20
29,10134.0,2024-07-28,Maison,Oujda,933920.85,104.5,6.0,9229.14
30,10128.0,2024-07-31,Studio,Casablanca,392307.07,35.3,1.0,11490.19
31,10024.0,2024-08-04,Studio,Youssoufia,171926.09,31.4,1.0,5536.43
32,10167.0,07/06/2024,Studio,Tanger,464555.93,32.0,1.0,14763.59
33,10125.0,17/12/2024,Villa,Casablanca,12500693.43,689.0,10.0,19693.18
34,10097.0,18/10/2024,Appartement,Marrakech,1082969.32,53.2,3.0,20051.64

---

### 3. Statistiques Centrales et de Dispersion
- Calculez la moyenne, la médiane et l'écart-type du prix de vente.
- Déterminez le prix minimum et le prix maximum enregistrés.
- Calculez le coefficient de variation (écart-type / moyenne) pour évaluer la dispersion des prix.

---

In [3]:
print(f"Mean: {df["prix_vente"].mean()}")
print(f"Median: {df["prix_vente"].median()}")
print(f"Ecart-type: {df["prix_vente"].std()}")
print(f"Prix Min: {df["prix_vente"].min()}")
print(f"Prix Max: {df["prix_vente"].max()}")

Mean: 1758123.6465714287
Median: 1082969.32
Ecart-type: 2239295.802319001
Prix Min: 171926.09
Prix Max: 12500693.43


### 4. Analyse par Segment (Agrégation)
- Calculez le prix de vente moyen pour chaque type de bien (Appartement, Maison, Loft).
- Comptez le nombre de ventes réalisées par ville.
- Trouvez la ville où le prix au mètre carré moyen est le plus élevé.

---

In [5]:
PrixMoyenParType = df.groupby("type_bien")["prix_vente"].mean()
print(PrixMoyenParType)

type_bien
Appartement    1.122209e+06
Maison         1.592372e+06
Riad           3.323043e+06
Studio         3.366584e+05
Villa          8.327965e+06
Name: prix_vente, dtype: float64

In [7]:
print(f"Nombre de ventes réalisées par ville: {df["ville"].value_counts()}")

Nombre de ventes réalisées par ville: ville
Fès           5
Oujda         4
Tétouan       4
Safi          4
Agadir        4
El Jadida     3
Casablanca    3
Kénitra       2
Tanger        2
Marrakech     2
Youssoufia    2
Name: count, dtype: int64

In [8]:
moyenPrixParVille = df.groupby("ville")["prix_m2"].mean()
print(f"Ville avec max prix moyen: {moyenPrixParVille.idxmax()}")
print(f"Ville avec max prix moyen: {moyenPrixParVille.max()}")

Ville avec max prix moyen: Marrakech
Ville avec max prix moyen: 16357.880000000001

### 5. Distribution et Quartiles
- Affichez les statistiques descriptives complètes du DataFrame avec une seule méthode.
- Identifiez le 75ème percentile de la surface des biens vendus.

---

In [10]:
df.describe(include="all")

,id_transaction,date,type_bien,ville,prix_vente,surface_m2,nombre_pieces,prix_m2
count,35.000000,35,35,35,3.500000e+01,35.000000,35.000000,33.000000
unique,NaN,33,5,11,NaN,NaN,NaN,NaN
top,NaN,2024-06-29,Maison,Fès,NaN,NaN,NaN,NaN
freq,NaN,2,13,5,NaN,NaN,NaN,NaN
mean,10107.314286,NaN,NaN,NaN,1.758124e+06,175.560000,4.142857,10302.109697
std,47.188465,NaN,NaN,NaN,2.239296e+06,158.624424,2.522171,4249.477620
min,10013.000000,NaN,NaN,NaN,1.719261e+05,24.500000,1.000000,5014.540000
25%,10079.500000,NaN,NaN,NaN,4.598473e+05,47.650000,2.000000,6407.600000
50%,10119.000000,NaN,NaN,NaN,1.082969e+06,111.700000,4.000000,9229.140000
75%,10140.500000,NaN,NaN,NaN,2.033838e+06,251.750000,6.000000,12556.750000
max,10178.000000,NaN,NaN,NaN,1.250069e+07,689.000000,10.000000,20051.640000

In [12]:
print(df.surface_m2.quantile(0.75))

251.75


### 6. Bonus : Analyse Temporelle
- Convertissez la colonne `Date` au format datetime.
- Quelle est la somme totale des ventes réalisée pour chaque mois ?

In [13]:
df.date=pd.to_datetime(df.date,format="mixed")

df.dtypes

id_transaction           float64
date              datetime64[ns]
type_bien                 object
ville                     object
prix_vente               float64
surface_m2               float64
nombre_pieces            float64
prix_m2                  float64
dtype: object

In [16]:
result = df.groupby(df.date.dt.month)["id_transaction"].count()
result

date
1     5
2     2
3     1
4     2
5     2
6     4
7     5
8     2
9     3
10    5
11    2
12    2
Name: id_transaction, dtype: int64